### ISSUE TITLE
Create admin page for Adopt-A-Book and password protect it

### ISSUE THREAD

**Issue by hortongn** [uclibs/adopt-a-book-old#10]
Depends on #9

Verify that Christa has the access she needs to the database to manage adopted books, take books out of a pending state, etc.

**Comment by haitzlm** [comment]
2/6/20- Added help ticket to Dennis Gavin to expand ldap access group for db admin area.

**Comment by lisa3711** [comment]
URL for Production:
https://libapps.libraries.uc.edu/adoptabook/db/index.php/main/main_book/

**Comment by haitzlm** [comment]
Updated- can view here, though still in progress.

**Comment by hortongn** [comment]
Christa can access the database, but we still need to password protect it.

**Comment by hortongn** [comment]
(sorted by title)

### Pending Books
* [edit button] Title 1, author, pub date, recognition, library name
* [edit button] Title 2

### Available Books
* [edit button] Title 3

### Adopted Books
* [edit button] Title 4

-----------------------

## Editing Title 1

adoption timestamp (info only)

adoption cost (info only)

adopter_fname

adopter l_name

adopter_phone

adopter_email

adoption status (as a drop down with labels)

dedication field (75 char limit)

recognition field (75 char limit)

[save button]

**Comment by hortongn** [comment]
@priyakvs Admin page is looking good.  Here are some requested changes:

Order the fields on the edit page the same way listed in the comment up above ⬆️ 

The adopter first last phone and email fields should be editable.  Only the timestamp and cost should be read-only.

On the edit page, let's just have 1 update button.  Have it save and then go back to the list.  Call the button "Save"

Make the Recognition field a <textbox> as well and limit it to 75 characters like the dedication field.

Let's have the "Adopted Books" section before the "Available Books" section.  Christa is more likely to have to edit adopted books than available books.  So they should be higher on the page.

Style changes
* Vertically align the text in each row to the top of the row
* Make the blue text black.  Blue text makes people think it's a link they can click on

**Comment by hortongn** [comment]
@priyakvs All of the changes look great.  You had mentions a message showing on the admin page after someone saved changes, but I'm not seeing it after I edit something.

**Comment by hortongn** [comment]
@priyakvs The admin form is looking good!  My suggestions are below.

The admin password and timeout are good.  Please go ahead and set it to 8 hours.

admin.php page
* Please show the word for adoption status instead of just the 1,2,3 number
* display the first and last adopter name as just a single "Name" field.  
* No data is showing the in Author field
* bottom-align the column headers so they are even.

edit.php page
* right-align the field names so the right-side of the name is next to the field.
* Make the Library field read only.  I don't think we want her to edit that
* Add Adoption Type field ("Preserve for the Future, etc.)
* Move the adoption status field up above the timestamp field

Also, can you remove the day of the week from the timestamp?
  `Thursday 14th of March 2019 06:50:28 PM` -> `14th of March 2019 06:50:28 PM`

Rename the "Adoption Year" field to "Event Year"

**Comment by priyakvs** [comment]
I have completed all changes and have updated to Dev. Please review and let me know for any additions. In the edit page, adoption type is already there as category. Please let me know if I should change the name of the field.

I am still working on the date format. Will get it done today.

**Comment by priyakvs** [comment]
Date format is now changed and updated.

**Comment by hortongn** [comment]
@priyakvs Everything looks good!  So it looks like you still need to make the Save work?  When I edit a record my changes don't stay.
