### ISSUE TITLE
Changes to user's email

### ISSUE THREAD

**Issue by priyakvs** [uclibs/adopt-a-book-old#20]
FROM header should be Christa’s address
Remove paragraph with the payment link
Tell the user they will also receive a separate email for the Foundation payment.
Include Christa’s contact information (email & phone)

**Comment by priyakvs** [comment]
Changes are done. Please check and let me know if additional changes are required.

**Comment by hortongn** [comment]
My suggestion for how the email should read.  Thoughts, Lisa?

```
Subject: UC Libraries Adopt-A-Book confirmation

Thank you for adopting a book from UC Libraries!  Your pre-order is complete.  You will also receive a confirmation email from the UC Foundation after your payment is complete.

If you have any questions, please contact Christa Bernardo at +1(513)556-0055 or bernarct@ucmail.uc.edu.
```
