### ISSUE TITLE
Minor changes to review and confirmation messages.

### ISSUE THREAD

**Issue by priyakvs** [uclibs/adopt-a-book-old#21]
Darken review message and confirmation messages.
Add a line indicating that user might have to enter duplicate information in the foundations page.

**Comment by priyakvs** [comment]
Done and updated in Dev. Please check

**Comment by hortongn** [comment]
Can we use this text instead?  Thoughts, Lisa?

`Thank you.  Click OK to be redirected to the payment page where you will be asked to enter your billing details.`
