### ISSUE TITLE
Site style tweaks (low priority)

### ISSUE THREAD

**Issue by hortongn** [uclibs/adopt-a-book-old#5]
May has several suggested style changes to the site.  Changes we can move forward on after the functional work is done are 

* Make the button styles consistent across the site
* Style the pagination buttons differently

We will verify the requested changes below when we have a chance to meet with May and Christa.

* Make standard text size larger
* Reduce usage of ALL CAPS
* Reduce animations on the sliding images
* changes to the site navigation style

**Comment by priyakvs** [comment]
Have changed buttons and size a little. Have removed use of caps except header links. Please check Dev

**Comment by haitzlm** [comment]
Thanks,I will come find you tomorrow and talk about images

**Comment by hortongn** [comment]
I think we can say that the style tweaks are complete.  May and Christa seemed happy with the site we demoed.
